version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: harvester-redis
    ports:
      - "12758:6379"
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:latest
    container_name: harvester-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: harvester
    ports:
      - "10864:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
